### ISSUE TITLE
Codemods I want to write

### ISSUE THREAD

**Issue by ajosedev** [ajosedev/codemods#2]
An on-going list of codemods I want to write, or problems I want to solve with codemods.

- [x] Auditing all uses of a given prop for a given component. #1
- [x] Rewrite import paths for a given module import. #3
- [x] Rename a component, including its import. e.g. `<SimpleButton />` -> `<Button />` #4 
- [ ] Change prop name for a component. e.g. `<Dummy count="1" />` -> `<Dummy total="1" />`. Add test for renaming two different props.
- [ ] Auditing nested usage of components, e.g. all Buttons within a Stack. This could potentially expand into a CLI that accepts CSS selectors, like `document.querySelector`
- [ ] Updating SCSS tokens or similar. Might just be a simple search replace on a css/scss filter?
